<?php

/**
 * @file
 * Contains digital_serial_page.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_entity_presave().
 */
function digital_serial_page_entity_presave(EntityInterface $entity) {
  switch ($entity->bundle()) {

    case 'digital_serial_page':
      // Autofill empty page sort field using required page no field.
      $page_no = trim($entity->getPageNo());
      $page_sort = trim($entity->getPageSort());
      if (empty($page_sort)) {
        $entity->setPageSort(str_pad($page_no, 4, "0", STR_PAD_LEFT));
      }

      // Avoid multiple whitespaces.
      $entity->set(
        'page_ocr',
        preg_replace(
          '!\s+!',
          ' ',
          $entity->get('page_ocr')->value
        )
      );
      break;
  }
}

/**
 * Implements hook_help().
 */
function digital_serial_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_serial_page module.
    case 'help.page.digital_serial_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Digital serial page content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function digital_serial_page_theme() {
  return [
    'digital_serial_page' => [
      'render element' => 'children',
    ],
  ];
}
