<?php

/**
 * @file
 * Contains digital_serial_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function digital_serial_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_serial_page module.
    case 'help.page.digital_serial_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Digital serial page content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function digital_serial_page_theme() {
  return [
    'digital_serial_page' => [
      'render element' => 'children',
    ],
  ];
}
