version: '3.6'

services:
  drupal-mysql-lib-unb-ca:
    image: mysql:5.7
    restart: always
    command: mysqld --skip-name-resolve --max_allowed_packet=64M
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"
    networks:
    - newspapers.lib.unb.ca

  drupal-redis-lib-unb-ca:
    image: redis:5-alpine
    restart: always
    expose:
      - "6379"
    networks:
      - newspapers.lib.unb.ca
    env_file:
      - ./env/redis.env

  drupal-solr-lib-unb-ca:
    image: unblibraries/solr-drupal:8.x-3.x
    expose:
    - "8983"
    networks:
    - newspapers.lib.unb.ca
    entrypoint:
    - docker-entrypoint-multiple.sh
    - newspapers.lib.unb.ca:/solr-conf
    - pages.newspapers.lib.unb.ca:/solr-conf

  mailhog:
    image: mailhog/mailhog
    expose:
      - "1025"
      - "8025"
    ports:
      - "4095:8025"
    networks:
      - newspapers.lib.unb.ca

  newspapers.lib.unb.ca:
    build:
      context: .
      args:
        - COMPOSER_DEPLOY_DEV=dev
    restart: always
    container_name: newspapers.lib.unb.ca
    depends_on:
      - drupal-mysql-lib-unb-ca
      - drupal-solr-lib-unb-ca
    expose:
      - "80"
    ports:
      - "3095:80"
    networks:
      - newspapers.lib.unb.ca
    env_file:
      - ./env/drupal.env
    environment:
      - DRUPAL_IMPORT_CONTENT=TRUE
    volumes:
      - ./config-yml:/app/configuration
      - ./content:/app/content
      - ./custom/modules:/app/modules/custom
      - ./custom/themes:/app/themes/custom
      - ./tests:/app/tests

networks:
  newspapers.lib.unb.ca:
    name: newspapers.lib.unb.ca
