version: '2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    command: mysqld --skip-name-resolve --max_allowed_packet=64M
    env_file:
      - ./env/mysql.env
    expose:
     - "3306"

  drupal-elasticsearch-lib-unb-ca:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - "cluster.name=drupal-elasticsearch-lib-unb-ca"
      - "network.host=0.0.0.0"
      - "discovery.zen.minimum_master_nodes=1"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.watcher.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    expose:
     - "9200"

  newspapers.lib.unb.ca:
    build:
      context: .
      args:
        - COMPOSER_DEPLOY_DEV=dev
    restart: always
    container_name: newspapers.lib.unb.ca
    expose:
      - "80"
    ports:
      - "3095:80"
    env_file:
      - ./env/drupal.env
    volumes:
      - ./config-yml:/app/configuration
      - ./custom/modules:/app/modules/custom
      - ./custom/themes:/app/themes/custom
      - ./tests:/app/tests
