<?php

/**
 * @file
 * Contains digital_serial_issue.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\Views;

/**
 * Implements hook_help().
 */
function digital_serial_issue_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_serial_issue module.
    case 'help.page.digital_serial_issue':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Digital Serial Issue') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function digital_serial_issue_theme() {
  return [
    'digital_serial_issue' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_entity().
 */
function digital_serial_issue_preprocess_digital_serial_issue(&$variables) {
  $variables['issue_entity'] = $variables['children']['#digital_serial_issue'];
  $variables['parent_title'] = $variables['issue_entity']->getParentTitle();
  $variables['metadata'] = [];

  $fields_to_parse = [
    'issue_title' => t('Issue Title'),
    'issue_volume' => t('Volume'),
    'issue_issue' => t('Issue'),
    'issue_edition' => t('Edition'),
    'issue_date' => t('Date'),
    'issue_missingp' => t('Missing Pages'),
    'issue_errata' => t('Errata'),
    'langcode' => t('Issue Language'),
    'issue_media' => t('Media'),
  ];

  foreach ($fields_to_parse as $field_name => $field_label) {
    if (!empty($variables['issue_entity']->$field_name->value)) {
      $variables['metadata'][$field_label->render()] = $variables['issue_entity']->$field_name->value;
    }
  }

  $view = Views::getView('digital_page_lister');
  $view->setDisplay('page_carousel');
  $view->setArguments([$variables['issue_entity']->id()]);
  $variables['page_list'] = $view->render();
}
