<?php

/**
 * @file
 * Contains digital_serial_issue.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\Views;

/**
 * Implements hook_help().
 */
function digital_serial_issue_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_serial_issue module.
    case 'help.page.digital_serial_issue':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Digital Serial Issue') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function digital_serial_issue_theme() {
  return [
    'digital_serial_issue' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_entity().
 */
function digital_serial_issue_preprocess_digital_serial_issue(&$variables) {
  $variables['issue_entity'] = $variables['children']['#digital_serial_issue'];

  $view = Views::getView('digital_serial_issue_page_list');
  $view->setDisplay('page_1');
  $view->setArguments([$variables['issue_entity']->id()]);
  $variables['page_list'] = $view->render();
}
