<?php

/**
 * @file
 * Contains serials.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function serials_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the serials module.
    case 'help.page.serials':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Serials Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_presave().
 */
function serials_serial_holding_presave(EntityInterface $entity) {
  // Flush cache so template variables refreshed after serial holding edits.
  drupal_flush_all_caches();
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function serials_serial_holding_delete(EntityInterface $entity) {
  // Flush cache so serial holding removed from display right after deletion.
  drupal_flush_all_caches();
}
