<?php

/**
 * @file
 * Contains panb_institution_import.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function panb_institution_import_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_serial_import module.
    case 'help.page.panb_institution_import':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PANB Institution Vocabulary Import Tool') . '</p>';
      return $output;

    default:
  }
}
