<?php

/**
 * @file
 * Contains digital_publication.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function digital_publication_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_publication module.
    case 'help.page.digital_publication':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Digital publication.') . '</p>';
      return $output;

    default:
  }
}
