<?php

/**
 * @file
 * Contains digital_serial_title.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function digital_serial_title_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_serial_title module.
    case 'help.page.digital_serial_title':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Digital serial title content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function digital_serial_title_theme() {
  return [
    'digital_serial_title' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_entity().
 */
function digital_serial_title_preprocess_digital_serial_title(&$variables) {
  // pass.
}
