<?php

/**
 * @file
 * Contains digital_serial_title.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\digital_serial_title\Entity\SerialTitleInterface;

/**
 * Implements hook_help().
 */
function digital_serial_title_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_serial_title module.
    case 'help.page.digital_serial_title':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Digital serial title content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function digital_serial_title_theme() {
  return [
    'digital_serial_title' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_entity().
 */
function digital_serial_title_preprocess_digital_serial_title(&$variables) {
  $variables['title_entity'] = $variables['children']['#digital_serial_title'];
  $variables['parent_publication'] = $variables['title_entity']->get('parent_title')->entity;
  $variables['digital_serial_title_id'] = $variables['title_entity']->id();

  $query = \Drupal::entityQuery('digital_serial_issue')
    ->condition('status', 1)
    ->condition('parent_title', $variables['title_entity']->id());
  $issue_results = $query->execute();
  $variables['title_issue_count'] = count($issue_results);

  if (!empty($issue_results)) {
    $query = \Drupal::entityQuery('digital_serial_page')
      ->condition('status', 1)
      ->condition('parent_issue', $issue_results, 'IN');
    $page_results = $query->execute();
    $variables['title_page_count'] = count($page_results);
  }
}

/**
 * Label callback for the SerialTitle entity.
 *
 * @param \Drupal\digital_serial_title\Entity\SerialTitleInterface $digital_serial_title
 *   The entity.
 *
 * @return string
 *   The string to serve as label.
 */
function digital_serial_title_format_label(SerialTitleInterface $digital_serial_title) {
  return $digital_serial_title->getParentPublication()->getTitle() . t(': Digital Issues');
}
