FROM docker.elastic.co/elasticsearch/elasticsearch:6.1.0
MAINTAINER UNB Libraries Systems <libsupport_at_unb.ca>

COPY config/elasticsearch/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
