<?php

/**
 * @file
 * Contains digital_publication_title.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function digital_publication_title_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the digital_publication_title module.
    case 'help.page.digital_publication_title':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Digital Publication Title') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function digital_publication_title_theme() {
  return [
    'digital_publication_title' => [
      'render element' => 'children',
    ],
  ];
}
