name: Deploy newspapers.lib.unb.ca
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  deploy:
    uses: unb-libraries/dockworker/.github/workflows/build-push-deploy-notify.yaml@6.x
    with:
      branch-env-map: '{"dev":"dev","prod":"prod"}'
      build-themes: true
      deploy-branches: '["dev","prod"]'
      image-name: 'ghcr.io/unb-libraries/newspapers.lib.unb.ca'
      k8s-deployment-name: 'newspapers-lib-unb-ca'
      push-branches: '["dev","prod"]'
      platforms: 'linux/amd64'
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GH_CONTAINER_REGISTRY_USER: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
